### PR TITLE
Cleanup Dockerfile

### PR DESCRIPTION
**Pull request by belak**
This adds 2 new settings: GITDIR_ADMIN_USER, and GITDIR_ADMIN_PUBLIC_KEY, which allow gitdir to auto-add a public key to the config on startup. This greatly simplifies the setup process and lines up with how many services are run in docker.

Unfortunately, between the last commit and now, travis-ci dropped their free option, so the CI is also being migrated to Github Actions. Finally, all packages and linters have been updated to their latest versions.

### CODE REVIEW

**Comment by belak** [comment]
CC @nirui since you opened the original Dockerfile PR.

**Comment by nirui** [comment]
Soo.... just want to popup to ask when will this change be merge&released? Thanks!

**Comment by belak** [comment]
Sorry, I meant to get to this ages ago, I've just got quite a bit going on IRL.

I'll merge this now to unblock people - if people have issues, definitely file bugs or PRs and I'll try to get to them. I would also be open to adding back using a non-root by default, but when I tried the original version I couldn't get it to work. PRs welcome.

**Comment by nirui** [comment]
Living the life is more important. Cheers dude! 🤗

**Pull request merged**
